---
title: "Titanic Survival Analysis Exploración"
output: html_document
date: "2024-03-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
library(tidyverse)
library(gt)
library(gtsummary)
library(skimr)
library(tidymodels)
library(modelsummary)
library(equatiomatic)
library(marginaleffects)
```

```{r}
ggplot2::theme_set(theme_bw())

color_1 = '#cc5058'
color_2 = '#6250cc'
```


```{r}

df <- train %>%
  janitor::clean_names() %>%
  mutate(across(all_of(c('sex', 'embarked')), ~ as.factor(.)))
```


```{r}
df
```



```{r setup , echo=FALSE , warning=FALSE}

library(reticulate)

```

```{r}
Sys.setenv(RETICULATE_PYTHON = "C:/Users/limco/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Anaconda3 (64-bit)/Anaconda Navigator.lnk")

```


```{python}

a = "¡Hola, mundo!"
print(a)

```

```{r}
df <- as.data.frame(df)
```



```{r}
library(reticulate)

# Pasar el dataframe de R a Python
py$df <- df

```


```{python}
# Mostrar las primeras filas del DataFrame
print(df.head())
```
```{r}
library(tidyverse)
df <- df %>% 
  mutate(survived = factor(survived, levels=c('0','1')))
```


```{r}
df
```

```{r}
df$survived %>% levels()
```



